version: '3.9'
services:
  database:
    image: postgres
    container_name: database
    env_file:
      - ./env/database.env
    ports:
      - 5432:5432
    volumes:
      - database_vol:/var/lib/postgresql/data
  backend:
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      - database
    ports:
      - 8081:8080
      - 5555:5555 #prisma studio port
    env_file:
      - ./env/backend.env
    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules
  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - 3000:3000
    env_file:
      - ./env/frontend.env
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
volumes:
  database_vol:
